shiny::tabPanel(title="Cart",
                value = "cart",
                icon=shiny::icon("cart-shopping"),
                fluidRow(
                    column(9,
                           p("All products in my cart",class="h1_cart"),
                           br(),
                           hr(),
                           br(),
                           fluidRow(
                               column(8,
                                      p("Optical products (S2)",class="h1_onglet3"),
                                      br(),
                                      uiOutput("cart_s2")),
                               column(2,
                                      p("Selected changes",class="h1_onglet3"),
                                      br(),
                                      htmlOutput("select_s2")),
                               column(2,
                                      p("OSM selected",class="h1_onglet3"),
                                      br(),
                                      htmlOutput("osm_s2"))),
                           br(),
                           hr(),
                           br(),
                           fluidRow(
                               column(8,
                                      p("Radar products (S1)",class="h1_onglet4"),
                                      br(),
                                      uiOutput("cart_s")),
                               column(2,
                                      p("Selected changes",class="h1_onglet4"),
                                      br(),
                                      htmlOutput("select_s")),
                               column(2,
                                      p("OSM selected",class="h1_onglet4"),
                                      br(),
                                      htmlOutput("osm_s")))
                           ),
                    column(3,
                           wellPanel(
                           p("Contact information",class="h1_cart"),
                           br(),
                           p(brighter::with_red_star("Enter your email address")),
                           textInput("caption", label=NULL),
                           br(),
                           hr(),
                           br(),
                           p(brighter::with_red_star("Select one or more types of output")),
                           awesomeCheckboxGroup(inputId = "output_choice",
                                                          label = NULL,
                                                          choices = c("Report (.pdf)",
                                                          "Shapefiles (.shp)"),
                                                          selected = NULL),
                           br(),
                           br(),
                           actionBttn(inputId = "validation_final",
                                                label = "Validate order",
                                                block = TRUE,
                                                icon= icon("paper-plane"),
                                                style = "material-flat",
                                                color = "warning")))

                )
)
